  - name: Build apk
  # You may pin to the exact commit or the version.
  # uses: MirkoMajkicProductDock/BuildAPK@24cc2d17f0c8e391166603bffe50f207b9d75859
  uses: MirkoMajkicProductDock/BuildAPK@v0.0.1
  with:
    # Pass the flavour you want to build artefacts for
    flavour: # optional, default is release
          
