 - name: APK action
  # You may pin to the exact commit or the version.
  # uses: WaterLemons2k/apk-action@cfbbcbcf022ff828ee59f4c30fba177f27c95324
  uses: WaterLemons2k/apk-action@v1.0.1
  with:
    # Contents of the keystore file (.jks), base64 encoded
    keystore: 
    # Password of the keystore
    keystore-password: 
    # Alias of the key
    key-alias: 
    # Password of the key
    key-password: 
    # The Java version to set up
    java-version: # optional
    # The arguments passed to Gradle
    gradle-args: # optional, default is --no-daemon
          
